spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  config:
    import: optional:application-secret.yml

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8080

jwt:
  secret:
    key: ${JWT_SECRET_KEY}